version: '3'

services:
  mongo:
    container_name: MongoDB
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mongo1234!
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network
  mongo-express:
    container_name: MongoExpress
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: MongoDB
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress1234!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Mongo1234!
    links:
      - mongo
    networks:
      - mongo-compose-network


networks:
    mongo-compose-network:
      driver: bridge